### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by lanrat** [KonradIT/gopro-gps-extract#1]
An example would be helpful.

Thanks.

**Comment by KonradIT** [comment]
this was a work in progress but I had to leave it because of exams. there are other projects available from @GoPro and @StillDavid

**Comment by lanrat** [comment]
Thanks!

Good luck on your Exams!

**Comment by KonradIT** [comment]
@lanrat check out [gopro-utils](http://github.com/stilldavid/gopro-utils) ([my fork includes more stuff](http://github.com/konradit/gopro-utils)). This project will be deprecated.
